window.MEU_BOLSO_ARTICLES_TESES = [
  {
    id: "lume-1433",
    title: "Tolerância a falhas e reflexão computacional num ambiente distribuído",
    authors: "Pavan, Willingthon",
    year: 2007,
    venue: "Dissertação - UFRGS (Lume)",
    tema: 'teses',
    filename: "toler-ncia-a-falhas-e-reflex-o-computacional-num-ambiente-di.pdf",
    localPath: "artigos/teses/toler-ncia-a-falhas-e-reflex-o-computacional-num-ambiente-di.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1433/1/000177712.pdf",
    summary: "O modelo de objetos apresenta-se como um modelo promissor para o desenvolvimento de software tolerante a falhas em virtude de características inerentes ao próprio modelo de objetos, tais como abstração de dados, encapsulamento, herança e reutilização de objetos (componentes). O uso de técnicas orientadas a objetos facilita o controle da complexidade do sistema porque promove uma melhor estruturação de seus componentes e também permite que componentes já validados sejam reutilizados [LIS96]. Técnicas básicas para tolerância a falhas em software...",
    tags: ["teses", "tecnologia", "tolerancia-a-falhas", "sistemas-distribuidos", "computacao"]
  },
  {
    id: "lume-1892",
    title: "AAERO : ambiente de aprendizado para o ensino de redes de computadores orientado a problemas",
    authors: "Dutra, Renato Luís de Souza",
    year: 2007,
    venue: "Dissertação - UFRGS (Lume)",
    tema: 'teses',
    filename: "aaero-ambiente-de-aprendizado-para-o-ensino-de-redes-de-comp.pdf",
    localPath: "artigos/teses/aaero-ambiente-de-aprendizado-para-o-ensino-de-redes-de-comp.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1892/1/000361176.pdf",
    summary: "Atualmente, a sociedade tem experimentado uma grande transformação devido à crescente incorporação da tecnologia em seu cotidiano. Estas mudanças demonstram o grande avanço tecnológico experimentado nas últimas décadas, principalmente na área de Redes e Telecomunicações. Este contexto tem gerado uma crescente procura por profissionais desta área, com um perfil que privilegie, além do conhecimento técnico, outras habilidades consideradas importantes, como o pensamento crítico, o auto-aprendizado e a habilidade para trabalhar em equipe, habilidad...",
    tags: ["teses", "tecnologia", "redes-de-computadores", "ensino", "telecom"]
  },
  {
    id: "lume-1473",
    title: "Sistema de controle de consumo para redes de computadores",
    authors: "Krolow, Roger al-Alam",
    year: 2007,
    venue: "Dissertação - UFRGS (Lume)",
    tema: 'teses',
    filename: "sistema-de-controle-de-consumo-para-redes-de-computadores.pdf",
    localPath: "artigos/teses/sistema-de-controle-de-consumo-para-redes-de-computadores.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1473/1/000193228.pdf",
    summary: "Este trabalho define e implementa um sistema de controle de consumo para redes de computadores, objetivando aumentar o tempo de operação da rede em caso de operação com recursos limitados e redução de consumo de energia em situações de fornecimento normal. Na definição do sistema, denominado NetPower, foi estabelecida uma estrutura através da qual um gerente (coordenador) monitora as atividades dos equipamentos vinculados à rede, e determina alterações nos estados de consumo respectivos, de acordo com as necessidades ou atendimento de padrões d...",
    tags: ["teses", "tecnologia", "redes", "consumo-energia", "iot"]
  },
  {
    id: "lume-1650",
    title: "Um Sistema multiagente para o Simulador Soccerserver",
    authors: "Bagatini, Daniela Duarte da Silva",
    year: 2007,
    venue: "Dissertação - UFRGS (Lume)",
    tema: 'teses',
    filename: "um-sistema-multiagente-para-o-simulador-soccerserver.pdf",
    localPath: "artigos/teses/um-sistema-multiagente-para-o-simulador-soccerserver.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1650/1/000214914.pdf",
    summary: "O interesse de pesquisa da comunidade de Inteligência Artificial em Sistemas Multiagentes tem gerado o crescimento da utilização de técnicas de agentes nas mais diversas áreas da ciência da computação. Isso ocorre, principalmente, devido à variedade de aplicações em que esses sistemas podem ser usados, como por exemplo: jogos de computadores, interfaces adaptativas, simulação e controle de processos industriais. The Robot World Cup Initiative (RoboCup) é uma tentativa de estimular a área de Inteligência Artificial e, principalmente de Sistemas...",
    tags: ["teses", "tecnologia", "inteligencia-artificial", "sistemas-multiagentes", "robocup"]
  },
  {
    id: "lume-1631",
    title: "Desenvolvimento de regras de pronúncia para a síntese de fala em língua portuguesa",
    authors: "Ostermann Filho, Paulo Eduardo",
    year: 2007,
    venue: "Dissertação - UFRGS (Lume)",
    tema: 'teses',
    filename: "desenvolvimento-de-regras-de-pron-ncia-para-a-s-ntese-de-fal.pdf",
    localPath: "artigos/teses/desenvolvimento-de-regras-de-pron-ncia-para-a-s-ntese-de-fal.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1631/1/000353974.pdf",
    summary: "Sabe-se que a fala é a principal maneira de comunicação entre as pessoas. A Síntese de fala (geração automática da fala pelo computador) tem recebido atenção da comunidade acadêmica e profissional por várias décadas. Ela envolve a conversão de um texto de entrada em fala, usando algoritmos e algumas formas de fala codificada. O texto pode ser digitado pelo teclado ou obtido por reconhecimento de caracteres ou, ainda, obtido de um banco de dados. A síntese de fala pode ser usada em vários domínios de aplicação, tais como: auxílio para deficiente...",
    tags: ["teses", "tecnologia", "processamento-de-audio", "sintese-de-fala", "linguagem"]
  },
  {
    id: "lume-1684",
    title: "Aplicação de técnicas de descobrimento de conhecimento em bases de dados e de inteligência artificial em avaliação de imóveis",
    authors: "Gonzalez, Marco Aurelio Stumpf",
    year: 2007,
    venue: "Tese - UFRGS (Lume)",
    tema: 'teses',
    filename: "aplica-o-de-t-cnicas-de-descobrimento-de-conhecimento-em-bas.pdf",
    localPath: "artigos/teses/aplica-o-de-t-cnicas-de-descobrimento-de-conhecimento-em-bas.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1684/1/000355246.pdf",
    summary: "A comparação de dados de mercado é o método mais empregado em avaliação de imóveis. Este método fundamenta-se na coleta, análise e modelagem de dados do mercado imobiliário. Porém os dados freqüentemente contêm erros e imprecisões, além das dificuldades de seleção de casos e atributos relevantes, problemas que em geral são solucionados subjetivamente. Os modelos hedônicos de preços têm sido empregados, associados com a análise de regressão múltipla, mas existem alguns problemas que afetam a precisão das estimativas. Esta Tese investigou a utili...",
    tags: ["teses", "tecnologia", "inteligencia-artificial", "data-mining", "bases-de-dados"]
  },
  {
    id: "lume-1885",
    title: "Arquiteturas multi-tarefas simultâneas : SEMPRE : arquitetura SMT com capacidade de execução e escalonamento de processos",
    authors: "Goncalves, Ronaldo Augusto de Lara",
    year: 2007,
    venue: "Tese - UFRGS (Lume)",
    tema: 'teses',
    filename: "arquiteturas-multi-tarefas-simult-neas-sempre-arquitetura-sm.pdf",
    localPath: "artigos/teses/arquiteturas-multi-tarefas-simult-neas-sempre-arquitetura-sm.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1885/1/000311415.pdf",
    summary: "O avanço tecnológico no projeto de microprocessadores, nos recentes anos, tem seguido duas tendências principais. A primeira tenta aumentar a freqüência do relógio dos mesmos usando componentes digitais e técnicas VLSI mais eficientes. A segunda tenta explorar paralelismo no nível de instrução através da reorganização dos seus componentes internos. Dentro desta segunda abordagem estão as arquiteturas multi-tarefas simultâneas, que são capazes de extrair o paralelismo existente entre e dentro de diferentes tarefas das aplicações, executando inst...",
    tags: ["teses", "tecnologia", "arquitetura-de-computadores", "paralelismo", "microprocessadores"]
  },
  {
    id: "lume-1466",
    title: "Imagens ecocardiográficas fetais integradas a banco de dados",
    authors: "Ramos, Eunice Santos da Silva",
    year: 2007,
    venue: "Dissertação - UFRGS (Lume)",
    tema: 'teses',
    filename: "imagens-ecocardiogr-ficas-fetais-integradas-a-banco-de-dados.pdf",
    localPath: "artigos/teses/imagens-ecocardiogr-ficas-fetais-integradas-a-banco-de-dados.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1466/1/000144060.pdf",
    summary: "Este trabalho discorre no escopo de informática médica, no âmbito da Unidade de Cardiologia Fetal do Instituto de Cardiologia - Fundação Universitária de Cardiologia do RS. Sabe-se que a medicina gera um grande volume de dados, sejam eles, textuais, numéricos, gráficos ou mesmo imagens ou sons geradas por equipamentos de ultra-som, tomógrafos computadorizados, ressonância magnética, RX, entre outros. Este trabalho desenvolve a integração das imagens ecocardiográficas fetais ao banco de dados. Atualmente, a tendência observada no desenvolvimento...",
    tags: ["teses", "tecnologia", "informatica-medica", "banco-de-dados", "imagens-medicas"]
  },
  {
    id: "lume-1622",
    title: "APSEE-Reuse : um meta-modelo para apoiar a reutilização de processos de software",
    authors: "Reis, Rodrigo Quites",
    year: 2007,
    venue: "Tese - UFRGS (Lume)",
    tema: 'teses',
    filename: "apsee-reuse-um-meta-modelo-para-apoiar-a-reutiliza-o-de-proc.pdf",
    localPath: "artigos/teses/apsee-reuse-um-meta-modelo-para-apoiar-a-reutiliza-o-de-proc.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1622/1/000353745.pdf",
    summary: "Dentre as principais áreas que constituem a Ciência da Computação, uma das que mais influenciam o mundo atual é a Engenharia de Software, envolvida nos aspectos tecnológicos e gerenciais do processo de desenvolvimento de software. Software tornou-se a base de sustentação de inúmeras organizações dos mais diversos ramos de atuação espalhados pelo planeta, consistindo de um elemento estratégico na diferenciação de produtos e serviços atuais. Atualmente, o software está embutido em sistemas relacionados a infindável lista de diferentes ciências e...",
    tags: ["teses", "tecnologia", "engenharia-de-software", "reuso", "processos"]
  },
  {
    id: "lume-1929",
    title: "Recuperação com base em Checkpointing : uma abordagem orientada a objetos",
    authors: "Silva, Francisco Assis da",
    year: 2007,
    venue: "Dissertação - UFRGS (Lume)",
    tema: 'teses',
    filename: "recupera-o-com-base-em-checkpointing-uma-abordagem-orientada.pdf",
    localPath: "artigos/teses/recupera-o-com-base-em-checkpointing-uma-abordagem-orientada.pdf",
    sourceUrl: "https://lume.ufrgs.br/bitstream/10183/1929/1/000361948.pdf",
    summary: "Independentemente do modelo de programação adotado, no projeto e implementação de aplicações de alta disponibilidade, faz-se necessário usar procedimentos de tolerância a falhas. Dentre as atividades que trazem consigo interesse de pesquisa na área de Tolerância a Falhas, estão os mecanismos de recuperação em um sistema computacional. Do ponto de vista prático, estes mecanismos buscam manter próximo do mínimo o tempo total de execução de aplicações computacionais de longa duração, ao mesmo tempo em que as preparam para não sofrerem perdas signi...",
    tags: ["teses", "tecnologia", "tolerancia-a-falhas", "checkpointing", "sistemas-distribuidos"]
  }
];
